# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  marilynbarefoot.com:
    site_hosts:
    - canonical: marilynbarefoot.com
      redirects:
      - www.marilynbarefoot.com
    local_path: ../site
    branch: master
    repo: git@github.com:artshostak/marilynbarefoot.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
